"""empty message

Revision ID: 4f8c0d719765
Revises: f68a6d09fa6e
Create Date: 2017-12-05 20:06:13.731863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8c0d719765'
down_revision = 'f68a6d09fa6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduleevents', sa.Column('user_edited', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduleevents', 'user_edited')
    # ### end Alembic commands ###
