"""empty message

Revision ID: 5ec6356ea9e0
Revises: 4f8c0d719765
Create Date: 2017-12-05 20:48:36.253793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec6356ea9e0'
down_revision = '4f8c0d719765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('scheduleEvent_link', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'scheduleEvent_link')
    # ### end Alembic commands ###
