"""empty message

Revision ID: 7a0d3eb76c71
Revises: 9052767a7826
Create Date: 2017-12-05 21:02:12.594726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a0d3eb76c71'
down_revision = '9052767a7826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'scheduleEvent_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('scheduleEvent_link', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
