"""empty message

Revision ID: 8329aaf14ffa
Revises: d5e789aaa64d
Create Date: 2017-12-01 17:40:31.313743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8329aaf14ffa'
down_revision = 'd5e789aaa64d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('scheduleevents', 'priority')
    op.add_column('users', sa.Column('last_reminder', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('reminder_frequency', sa.Time(), nullable=True))
    op.create_index(op.f('ix_users_last_reminder'), 'users', ['last_reminder'], unique=False)
    op.create_index(op.f('ix_users_reminder_frequency'), 'users', ['reminder_frequency'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_reminder_frequency'), table_name='users')
    op.drop_index(op.f('ix_users_last_reminder'), table_name='users')
    op.drop_column('users', 'reminder_frequency')
    op.drop_column('users', 'last_reminder')
    #op.add_column('scheduleevents', sa.Column('priority', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
