"""empty message

Revision ID: 9052767a7826
Revises: 5ec6356ea9e0
Create Date: 2017-12-05 20:59:17.302850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9052767a7826'
down_revision = '5ec6356ea9e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('events', 'scheduleEvent_link')
    op.add_column('scheduleevents', sa.Column('event_link', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduleevents', 'event_link')
    op.add_column('events', sa.Column('scheduleEvent_link', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
