"""empty message

Revision ID: d5e789aaa64d
Revises: 
Create Date: 2017-11-30 17:54:18.452203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e789aaa64d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_scheduleevents_priority', table_name='scheduleevents')
    # op.drop_column('scheduleevents', 'priority')
    ### end Alembic commands ###


def downgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('scheduleevents', sa.Column('priority', sa.INTEGER(), nullable=True))
    # op.create_index('ix_scheduleevents_priority', 'scheduleevents', ['priority'], unique=False)
    ### end Alembic commands ###
