"""empty message

Revision ID: f68a6d09fa6e
Revises: 0d578a14babc
Create Date: 2017-12-02 01:40:07.872039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f68a6d09fa6e'
down_revision = '0d578a14babc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduleevents') as batch_op:
       batch_op.drop_column('priority')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduleevents', sa.Column('priority', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
